machines:
  - name: three-rivers
    dataset:
      type: TimeSeriesDataset
      tags: 
      - UON_EF.OPCIS::LO006-B1H.PRCASXIN
      - UON_EF.OPCIS::LO006-B1H.PRTUBXIN
      - UON_EF.OPCIS::LO006-B1H_M1.PRSTAXIN
      - UON_EF.OPCIS::LO006-B1H_M1.RTGASDIN
      train_start_date: 2018-06-10T00:00:00+01:00
      train_end_date: 2018-07-20T00:00:00+01:00
    model:
      sklearn.pipeline.Pipeline:
        steps:
        - sklearn.pipeline.FeatureUnion:
          - sklearn.preprocessing.data.RobustScaler
        - gordo_components.model.models.KerasAutoEncoder:
            kind: feedforward_model
            enc_dim: [3,2]
            dec_dim: [3]
            enc_func: [tanh,tanh]
            dec_func: [tanh]
